ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'active' NOT NULL;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "department" text;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "location" text;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "employment_type" text;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "hiring_manager_user_id" text;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "recruiter_user_id" text;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
ALTER TABLE "job_criteria" ADD COLUMN IF NOT EXISTS "name" text;
UPDATE "job_criteria" SET "name" = COALESCE("name", "label", 'Criterion');
ALTER TABLE "job_criteria" ALTER COLUMN "name" SET NOT NULL;
ALTER TABLE "job_criteria" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "candidates" ADD COLUMN IF NOT EXISTS "full_name" text;
UPDATE "candidates" SET "full_name" = COALESCE("full_name", "display_name", 'Candidate');
ALTER TABLE "candidates" ALTER COLUMN "full_name" SET NOT NULL;
ALTER TABLE "candidates" ADD COLUMN IF NOT EXISTS "source" text;
ALTER TABLE "candidates" ADD COLUMN IF NOT EXISTS "resume_url" text;
ALTER TABLE "candidates" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
ALTER TABLE "applications" ADD COLUMN IF NOT EXISTS "organization_id" text;
UPDATE "applications" a SET "organization_id" = j."organization_id" FROM "jobs" j WHERE a."job_id" = j."id" AND a."organization_id" IS NULL;
ALTER TABLE "applications" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'active' NOT NULL;
ALTER TABLE "applications" ADD COLUMN IF NOT EXISTS "applied_at" timestamptz;
ALTER TABLE "applications" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "application_id" text;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "doc_type" text DEFAULT 'resume' NOT NULL;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "file_url" text DEFAULT '' NOT NULL;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "parsed_content" jsonb;
ALTER TABLE "assessments" ADD COLUMN IF NOT EXISTS "organization_id" text;
UPDATE "assessments" a SET "organization_id" = ap."organization_id" FROM "applications" ap WHERE a."application_id" = ap."id" AND a."organization_id" IS NULL;
ALTER TABLE "assessments" ADD COLUMN IF NOT EXISTS "assessment_type" text;
ALTER TABLE "assessments" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'pending' NOT NULL;
ALTER TABLE "assessments" ADD COLUMN IF NOT EXISTS "notes" text;
ALTER TABLE "assessments" ADD COLUMN IF NOT EXISTS "assessed_by_user_id" text;
ALTER TABLE "criterion_scores" ADD COLUMN IF NOT EXISTS "job_criterion_id" text;
UPDATE "criterion_scores" SET "job_criterion_id" = "criterion_id" WHERE "job_criterion_id" IS NULL;
ALTER TABLE "criterion_scores" ADD COLUMN IF NOT EXISTS "notes" text;
ALTER TABLE "ranking_snapshots" ADD COLUMN IF NOT EXISTS "organization_id" text;
UPDATE "ranking_snapshots" r SET "organization_id" = j."organization_id" FROM "jobs" j WHERE r."job_id" = j."id" AND r."organization_id" IS NULL;
ALTER TABLE "ranking_snapshots" ADD COLUMN IF NOT EXISTS "snapshot_data" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE "ranking_snapshots" ADD COLUMN IF NOT EXISTS "generated_at" timestamptz;
ALTER TABLE "integration_connections" ADD COLUMN IF NOT EXISTS "account_email" text;
ALTER TABLE "integration_connections" ADD COLUMN IF NOT EXISTS "provider_metadata" jsonb;
ALTER TABLE "integration_connections" ADD COLUMN IF NOT EXISTS "connected_at" timestamptz;
ALTER TABLE "integration_connections" ADD COLUMN IF NOT EXISTS "last_synced_at" timestamptz;
ALTER TABLE "interview_drafts" ADD COLUMN IF NOT EXISTS "organization_id" text;
UPDATE "interview_drafts" d SET "organization_id" = a."organization_id" FROM "applications" a WHERE d."application_id" = a."id" AND d."organization_id" IS NULL;
ALTER TABLE "interview_drafts" ADD COLUMN IF NOT EXISTS "created_by_user_id" text;
ALTER TABLE "interview_drafts" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'draft' NOT NULL;
ALTER TABLE "interview_drafts" ADD COLUMN IF NOT EXISTS "notes" text;
ALTER TABLE "interview_drafts" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
ALTER TABLE "interview_slots" ADD COLUMN IF NOT EXISTS "interview_draft_id" text;
UPDATE "interview_slots" SET "interview_draft_id" = "draft_id" WHERE "interview_draft_id" IS NULL;
ALTER TABLE "interview_slots" ADD COLUMN IF NOT EXISTS "start_time" timestamptz;
UPDATE "interview_slots" SET "start_time" = "start_at" WHERE "start_time" IS NULL;
ALTER TABLE "interview_slots" ADD COLUMN IF NOT EXISTS "end_time" timestamptz;
UPDATE "interview_slots" SET "end_time" = "end_at" WHERE "end_time" IS NULL;
ALTER TABLE "interviews" ADD COLUMN IF NOT EXISTS "organization_id" text;
UPDATE "interviews" i SET "organization_id" = a."organization_id" FROM "applications" a WHERE i."application_id" = a."id" AND i."organization_id" IS NULL;
ALTER TABLE "interviews" ADD COLUMN IF NOT EXISTS "interview_draft_id" text;
UPDATE "interviews" SET "interview_draft_id" = "draft_id" WHERE "interview_draft_id" IS NULL;
ALTER TABLE "interviews" ADD COLUMN IF NOT EXISTS "interview_slot_id" text;
ALTER TABLE "interviews" ADD COLUMN IF NOT EXISTS "scheduled_start" timestamptz;
ALTER TABLE "interviews" ADD COLUMN IF NOT EXISTS "scheduled_end" timestamptz;
ALTER TABLE "interviews" ADD COLUMN IF NOT EXISTS "location" text;
ALTER TABLE "interviews" ADD COLUMN IF NOT EXISTS "calendar_event_id" text;
UPDATE "interviews" SET "calendar_event_id" = "event_id" WHERE "calendar_event_id" IS NULL;
ALTER TABLE "interviews" ADD COLUMN IF NOT EXISTS "provider_metadata" jsonb;
ALTER TABLE "audit_events" ADD COLUMN IF NOT EXISTS "actor_user_id" text;
UPDATE "audit_events" SET "actor_user_id" = "actor_id" WHERE "actor_user_id" IS NULL;
ALTER TABLE "audit_events" ADD COLUMN IF NOT EXISTS "details" jsonb;
ALTER TABLE "audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamptz DEFAULT now() NOT NULL;
CREATE INDEX IF NOT EXISTS "organizations_status_idx" ON "organizations" ("status");
CREATE INDEX IF NOT EXISTS "jobs_org_status_idx" ON "jobs" ("organization_id", "status");
CREATE INDEX IF NOT EXISTS "applications_org_idx" ON "applications" ("organization_id");
CREATE INDEX IF NOT EXISTS "applications_job_stage_idx" ON "applications" ("job_id", "stage");
CREATE INDEX IF NOT EXISTS "assessments_org_idx" ON "assessments" ("organization_id");
CREATE INDEX IF NOT EXISTS "ranking_snapshots_org_idx" ON "ranking_snapshots" ("organization_id");
CREATE INDEX IF NOT EXISTS "integration_connections_provider_status_idx" ON "integration_connections" ("provider", "status");
CREATE INDEX IF NOT EXISTS "interview_drafts_org_idx" ON "interview_drafts" ("organization_id");
CREATE INDEX IF NOT EXISTS "interviews_org_status_idx" ON "interviews" ("organization_id", "status");
CREATE INDEX IF NOT EXISTS "audit_events_org_occurred_idx" ON "audit_events" ("organization_id", "occurred_at");
